### ISSUE TITLE
IE11 cannot spread non-iterable object

### ISSUE THREAD

**Issue by mvolkmann** [google/traceur-compiler#1861] opened 2015-04-02 15:59 UTC
I get this error using Traceur 0.0.88 in IE11, but not in Chrome.

let mySet = new Set();
mySet.add('foo').add('bar);
let myArr = [...mySet];

Why doesn't Traceur think mySet is iterable in IE11?

**Comment by arv** [comment] 2015-04-02 16:09
Duplicate of #1810

**Closed by arv** 2015-04-02 16:09 UTC
