### ISSUE TITLE
Error node 6

### ISSUE THREAD

**Issue by RWOverdijk** [google/traceur-compiler#2115] opened 2016-05-12 20:56 UTC
```
/usr/local/lib/node_modules/jspm/node_modules/traceur/bin/traceur.js:4941
      for (var name = void 0 in this.variableDeclarations) {
               ^^^^^^^^^^^^^
SyntaxError: for-in loop variable declaration may not have an initializer.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/jspm/node_modules/traceur/src/node/traceur.js:24:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
```

**Comment by arv** [comment] 2016-05-12 21:18
Dupe of #1951

Fixed in https://github.com/google/traceur-compiler/releases/tag/0.0.93

**Closed by arv** 2016-05-12 21:18 UTC

**Comment by RWOverdijk** [comment] 2016-05-12 21:19
I don't have this problem with node 5, just 6. That's from 2015. Are you sure that's the same thing?

**Comment by arv** [comment] 2016-05-13 01:49
Yup. We used to generate the code with the initializer in the for in loop. This was valid in ES5 but made invalid in ES6. Traceur was fixed to not generate invalid ES6 in the commit above.

**Comment by RWOverdijk** [comment] 2016-05-13 08:03
Alright, then I'll have to figure out why updating node causes older code to run. Weird. Thanks.

**Comment by arv** [comment] 2016-05-13 14:33
The code with the invalid code needs to be recompiled with a newer version of traceur.
