### ISSUE TITLE
memberVariables output bogus code with outputLanguage=es6

### ISSUE THREAD

**Issue by caitp** [google/traceur-compiler#1788] opened 2015-03-03 19:47 UTC
https://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--annotations%20--member-variables%20--output-language%3Des6%20--source-maps%20--type-assertions%20--types%20%0Aclass%20MyType%20%7B%7D%0Aclass%20C%20%7B%0A%20%20foo%3AMyType%3B%0A%7D%0A

for an example --- this is causing issues for "prod" builds of angular with outputLanguage=es6 (which is subsequently re-compiled to output as es5)

![screen shot 2015-03-03 at 2 46 01 pm](https://cloud.githubusercontent.com/assets/2294695/6470793/3dc7c312-c1b4-11e4-9446-9491e478027f.png)

**Comment by arv** [comment] 2015-03-03 20:16
@vicb

**Comment by caitp** [comment] 2015-03-03 20:28
https://github.com/angular/angular/blob/master/tools/transpiler/index.js#L176-L178 related to this --- the condition is removed in my local branch, because `options` is not exported anymore, so it's unknown whether the code is outputting as es6 or not. Need a better way of doing this =)

**Comment by vicb** [comment] 2015-03-03 21:04
@arv IIRC you've asked me to output this in ES6, don't you ?

**Comment by vicb** [comment] 2015-03-03 21:12
@arv I found [this comment](https://github.com/google/traceur-compiler/pull/1417#discussion_r18912187) in the orginal PR. As far as I remember I did update the write to output member variable declaration after that. May be I didn't get what you meant ?

**Comment by arv** [comment] 2015-03-03 21:16
@caitp We alway pass the options to the transformer now so this transformer can do something else when output is es6.

**Comment by arv** [comment] 2015-03-03 21:17
@vicb That was about being able to round trip the writer.

**Comment by caitp** [comment] 2015-03-03 21:21
@arv the ParseTreeWriter doesn't actually save the options object that it's passed, only the prettyPrint field. My PR addresses that, if you want to have a look

**Comment by vicb** [comment] 2015-03-04 07:32
What would be the right fix then ?
- Do not change the ParseTreeWriter (ie it would have the ability to output member variable declarations),
- Create a ES6-specific class transformer which would move mbr variable initialization in the constructor - static variables would be more challenging especially with class expressions.

**Comment by vicb** [comment] 2015-03-04 08:02
This issue is a duplicate of #1708

**Comment by arv** [comment] 2015-03-04 08:23
Closing this in favor of #1708

**Closed by arv** 2015-03-04 08:23 UTC
